export default {
  // 1. Manual Trigger (Browser Test)
  async fetch(request, env, ctx) {
    const result = await generateAndSendReport(env);
    return new Response(result, { headers: { "content-type": "text/plain" } });
  },

  // 2. Scheduled Trigger (Cron)
  async scheduled(event, env, ctx) {
    await generateAndSendReport(env);
    console.log("Daily report task finished.");
  }
};

async function generateAndSendReport(env) {
  // A. Find Yesterday's Complaints
  const { results } = await env.DB.prepare(`
    SELECT content FROM feedback 
    WHERE sentiment_label = 'NEGATIVE' 
    ORDER BY created_at DESC LIMIT 20
  `).all();

  if (!results || results.length === 0) {
     return "No negative feedback to report today!";
  }

  // B. AI Summary
  const textToAnalyze = results.map(r => r.content).join("\n");
  const aiRes = await env.AI.run('@cf/meta/llama-3-8b-instruct', {
    messages: [
      { role: "system", content: "Summarize these user complaints into 3 bullet points." },
      { role: "user", content: textToAnalyze }
    ]
  });
  const summary = aiRes.response;

  // C. Send Email via Resend's Test Domain
  // Note: You MUST use 'onboarding@resend.dev' if you don't have a domain.
  // Note: You can ONLY send to the email address you used to sign up for Resend.
  
  const emailResponse = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${env.RESEND_API_KEY}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      from: 'onboarding@resend.dev', // <--- DO NOT CHANGE THIS
      to: 'likhitakrovidi@gmail.com', // <--- CHANGE to your registered email
      subject: 'Daily Feedback Summary',
      html: `
        <h2>Daily Sentiment Report</h2>
        <p>Here are the top issues from the last 24 hours:</p>
        <div style="background:#f4f4f5; padding:20px; border-radius:8px;">
          <pre style="white-space: pre-wrap; font-family: sans-serif;">${summary}</pre>
        </div>
        <p><small>Generated by Cloudflare Workers AI</small></p>
      `
    })
  });

  if (emailResponse.ok) {
    return "Email sent successfully!";
  } else {
    return "Failed to send: " + await emailResponse.text();
  }
}